# Generated by Django 5.0.6 on 2024-05-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('alternative_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alternativ elektron pochta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=100)),
                ('qabul_kunlari', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('bakalavr_mutaxassisligi', models.TextField(blank=True, null=True)),
                ('magistratura_mutaxassisligi', models.TextField(blank=True, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='rahbariyat_profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='FIO')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Murojaat matni')),
                ('file', models.FileField(blank=True, null=True, upload_to='inquiry_files/', verbose_name='Fayl biriktirish')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='app_contact.contact', verbose_name='Bog’lanish')),
                ('rahbariyat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='app_contact.rahbariyat', verbose_name='Rahbariyat')),
            ],
        ),
    ]
