# Generated by Django 5.0.6 on 2024-05-10 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0001_initial'),
        ('app_leadership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='rahbariyat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='app_leadership.rahbariyat', verbose_name='Rahbariyat'),
        ),
        migrations.DeleteModel(
            name='Rahbariyat',
        ),
    ]
