# Generated by Django 5.0.6 on 2024-05-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0002_alter_inquiry_rahbariyat_delete_rahbariyat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='contact',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefon'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
