# Generated by Django 5.0.6 on 2024-05-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_elstandartsFound', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elstandartsfound',
            old_name='year',
            new_name='approved_year',
        ),
        migrations.RenameField(
            model_name='elstandartsfound',
            old_name='code',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='elstandartsfound',
            name='description',
        ),
        migrations.RemoveField(
            model_name='elstandartsfoundphoto',
            name='image',
        ),
        migrations.AddField(
            model_name='elstandartsfound',
            name='document_number',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elstandartsfound',
            name='document_type',
            field=models.CharField(default='default_type', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elstandartsfound',
            name='keyword',
            field=models.CharField(default='default_keyword', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elstandartsfound',
            name='name',
            field=models.CharField(default='default_keyword', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elstandartsfoundphoto',
            name='file',
            field=models.FileField(default='default_keyword', upload_to='elstandardsfound_files'),
            preserve_default=False,
        ),
    ]
