# Generated by Django 5.0.6 on 2024-05-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_elstandartsFound', '0002_rename_year_elstandartsfound_approved_year_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='elstandartsFound',
            new_name='elstandardsFound',
        ),
        migrations.RenameModel(
            old_name='elstandartsFoundPhoto',
            new_name='elstandardsFoundPhoto',
        ),
    ]
