# Generated by Django 5.0.6 on 2024-05-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=100)),
                ('qabul_kunlari', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('bakalavr_mutaxassisligi', models.TextField(blank=True, null=True)),
                ('magistratura_mutaxassisligi', models.TextField(blank=True, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='rahbariyat_profile_images/')),
            ],
        ),
    ]
