# Generated by Django 5.0.6 on 2024-05-10 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reglament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.CharField(max_length=20)),
                ('belgilanishi', models.CharField(max_length=20)),
                ('nomi', models.CharField(max_length=200)),
                ('hujjat', models.FileField(upload_to='reglament_files/')),
            ],
        ),
        migrations.CreateModel(
            name='ReglamentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('ko_rish', models.BooleanField(default=False)),
                ('reglament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='app_reglament.reglament')),
            ],
        ),
    ]
