# Generated by Django 5.0.6 on 2024-05-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reglament', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReglamentElement',
        ),
    ]
